### ISSUE TITLE
看了一下……

### ISSUE THREAD

**Issue by Arondight** [K-Guan/Arch_Linux_auto_upgrade#3]
1. 推荐使用`-yy` 而非`-y`，否则一次数据库同步出错以后会永远出错
+ 最好直接提供文件，把安装脚本分离出来，否则你做一次修改需要同时改动2 个脚本……
+ 输出重定向了把
+ python 我不太了解，但是如果python 的heredoc 和perl 类似的话，楼主的py 脚本生成的文件排版上是完全错乱的吧。
+ 不需要先`daemon-reload` 下么
+ 每次更新完最好删一下旧包，否则会cache 会越来越大
```shell
result=( $(pacman -Qqdt) )
if [[ 0 != ${#result[@]} ]]; then
  sudo pacman --noconfirm -R ${result[@]}
fi
sudo pacman --noconfirm -Sc
```

**Comment by K-Guan** [comment]
1. 哦？我一直都是`pacman -Syu`的，也就是说改成`pacman -Syyu`?
2.  实际纯属好玩而已，一个脚本已经够了。
3. 唉？什么输出重定向？
4. Python is the best!……当然不会。
5. 不懂～做什么用的？
6. 嗯……表示没那个习惯，官方wiki说留着会比较有用。而且需要的时候可以直接`pacman -Scc`嘛。

最后问下，您哪位？
